import { IWorkCard, Technologies } from './workCard-interface'; // Importa l'interfaccia

export const WORKS: IWorkCard[] = [
  {
    title: 'Questo portfolio',
    description: 'Angular può sembrare un framework troppo "overkill" per questa tipologia di progetto, ma quello che si vede è solo una piccola parte di ciò che nasconde al suo interno...',
    customer: "Myself",
    month: "Gen",
    year: 2025,
    workLink: 'https://www.esempio.com/progetto-angular',
    videoLink: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    technologies: [Technologies.angular, Technologies.Typescript, Technologies.figma],
  },
  {
    title: 'Sms Privacy sender',
    description: "Per un' operatore l'invio di molteplici sms a una grande mole di clienti e creare dei report può essere un'attività lunga e tediosa, con questa dashboard questo processo verrà ottimizzato...",
    customer: "Geomad Evolution",
    month: "Nov",
    year: 2024,
    workLink: 'https://www.esempio.com/sito-web-svelte',
    videoLink: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    technologies: [Technologies.nextjs, Technologies.Typescript, Technologies.node],
  },
  {
    title: 'Binocolo Studio',
    description: 'Agenzia video di Milano, hanno avuto la necessità di mostrare i loro lavori con ferrari, D&G, Tom Ford in un sito web che mettesse in primo piano i loro lavori con una estetica minimale...',
    customer: "Binocolo S.r.l",
    month: "Ott",
    year: 2024,
    workLink: 'https://www.esempio.com/blog-wordpress',
    videoLink: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    technologies: [Technologies.wordpress, Technologies.Javascript, Technologies.php, Technologies.Gsap, Technologies.figma],
  },
  {
    title: 'Meteo App',
    description: 'Piccola esercitazione di stile, integrare un api del meteo e visualizzarlo con un design moderno ed accattivante..',
    customer: "personal project",
    month: "Giu",
    year: 2024,
    workLink: 'https://www.esempio.com/applicazione-react',
    videoLink: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    technologies: [Technologies.react, Technologies.Javascript, Technologies.Gsap],
  },
  {
    title: 'Quiz Marketing',
    description: "Con questa web app un'agenzia di marketing avrà la possibilità di testare le conscienze dei propri clienti in svariati reparti di marketing fornendo dei voti e un report utile alla loro collaborazione...",
    customer: "Publikendi",
    month: "Giu",
    year: 2024,
    workLink: 'https://www.esempio.com/e-commerce-nextjs',
    videoLink: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    technologies: [Technologies.svelte, Technologies.firebase, Technologies.Javascript ],
  },
  {
    title: 'Tenute maestrale - Design',
    description: "Per l'apertura della nuova cantina delle tenute maestrale mi è stato richiesto di creare un design per una nuova versione del sito che mettesse in primo piano i loro vini e le loro guide...",
    customer: "Tenute Maestrale",
    month: "Gen",
    year: 2024,
    workLink: 'https://www.esempio.com/e-commerce-nextjs',
    videoLink: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    technologies: [Technologies.figma],
  },
  
];